---
# This playbook contains common actions that will be run on "all" hosts

# sudo apt-get update
- name: Update apt packages
  apt:
    update_cache: yes
  tags:
    - system

# sudo timedatectl set-timezone Europe/Berlin
- name: Set time zone to Europe/Berlin
  timezone:
    name: Europe/Berlin
  tags:
    - system

# Service systemd-resolved stoppen
- name: Stop and remove systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    state: stopped
    enabled: no

# delete old resolv.conf (unlink)
- name: Deleting old resolv.conf-file
  file:
    path: /etc/resolv.conf
    state: absent

# copy the new resolv.conf
- name: Set name-resolution
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf

# check tftp-Folder and create if not exists
- name: check directory /srv/www
  stat:
    path: /srv/tftp
  register: my_folder

- name: "echo if directory already exists"
  debug:
    msg: "the tftp directory already exists"
  when: my_folder.stat.exists

- name: "Create directory if not exists"
  file:
    path: /srv/tftp
    state: directory
    mode: 0755
    group: root
    owner: root
  when: my_folder.stat.exists is false

# sudo apt-get install dnsmasq
- name: Install dnsmasq
  apt:
    name: dnsmasq
    state: present
    update_cache: no
  tags:
    - dnsmasq

# Configure dnsmasq
- name: configure dnsmasq
  template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.d/pxe.conf
  notify: Restart dnsmasq
  tags:
    - dnsmasq

# Download pxe-Bootfile
- name: Download PXE-File
  get_url:
    url: http://archive.ubuntu.com/ubuntu/dists/focal/main/installer-amd64/current/legacy-images/netboot/ubuntu-installer/amd64/pxelinux.0
    dest: /srv/tftp/pxelinux.0

# sudo apt-get dist-upgrade
- name: Install distribution upgrades
  apt:
    upgrade: dist
  tags:
    - system

# sudo apt-get autoclean
- name: Remove useless apt packages from the cache
  apt:
    autoclean: yes
  tags:
    - system

# sudo apt-get autoremove
- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
  tags:
    - system